# Chapter10_심화문제

## 10.1

In [12]:
import numpy as np

In [13]:
num_arr = np.arange(1, 21)
print(num_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [14]:
num_arr2 = np.arange(20, 0, -1)
print(num_arr2)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [15]:
print('num_arr 내의 모든 원소의 합 :', num_arr.sum())

num_arr 내의 모든 원소의 합 : 210


In [16]:
print(num_arr.reshape(5, 4)) # 5행 4열의 배열로 변경

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## 10.2

(1)

In [2]:
import numpy as np

n_arr = np.arange(25)
n_arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

(2)

In [3]:
print('첫 원소 :', n_arr[0])
print('마지막 원소 :', n_arr[-1])

첫 원소 : 0
마지막 원소 : 24


(3)

In [4]:
n_arr.reshape(5, 5)[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

(4)

In [5]:
n_arr.reshape(5, 5)[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

(5)

In [8]:
a = n_arr.reshape(5,5)
print(a[:,::2])

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


(6)

In [9]:
a = n_arr.reshape(5,5)
print(a[::2,::2])

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


(7)

In [16]:
b = n_arr.reshape(5,5)[0:2,0:5].flatten()
b.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
print(n_arr.reshape(5,5)[0:2,0:5].reshape(5, 2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## 10.3

(1)

In [41]:
import numpy as np

a = np.random.rand(3, 3, 3)
a

array([[[0.67355221, 0.73092484, 0.93487874],
        [0.41645101, 0.2719192 , 0.31859944],
        [0.2242705 , 0.49331399, 0.64610337]],

       [[0.74784138, 0.19758447, 0.37287268],
        [0.94010236, 0.34788035, 0.86432942],
        [0.69859725, 0.10073625, 0.30538251]],

       [[0.18487012, 0.13108172, 0.57720049],
        [0.20019047, 0.76799976, 0.88268602],
        [0.68339301, 0.7302606 , 0.8727344 ]]])

(2)

In [43]:
print('a의 원소들 중 최댓값 :', a.max())

a의 원소들 중 최댓값 : 0.9401023587504533


(3)

In [45]:
print('a의 원소들 중 최댓값의 위치 :', a.argmax())

a의 원소들 중 최댓값의 위치 : 12


## 10.4

(1)

In [63]:
import numpy as np
 
a = np.array([i % 2 for i in range(1, 26)]) #체크판 열 생성
 
a.reshape(5, 5) # 5 * 5 사이즈로 만든다. 

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

(2)

In [67]:
import numpy as np
 
a = np.array([i % 2 for i in range(1, 26)])
b = a.reshape(5, 5)

print("행렬의 행 방향 성분의 합 :")
print('[', end = ' ')
for t in range(len(b)) :
    print(sum(b[:, t]), end = ' ') #행을 인덱싱해서 불러온다. 

print(']')

행렬의 행 방향 성분의 합 :
[ 3 2 3 2 3 ]


## 10.5

In [48]:
a = np.arange(0, 32).reshape(4, 4, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [55]:
print('10번째 원소 :', a[1][0][1])
print('20번째 원소 :', a[2][1][1])

10번째 원소 : 9
20번째 원소 : 19


In [58]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [60]:
print('10번째 원소 :', a.flatten()[9])
print('20번째 원소 :', a.flatten()[19])

10번째 원소 : 9
20번째 원소 : 19


In [66]:
import numpy as np

a = np.arange(0, 32).reshape(4, 4, 2)
b = a.flatten()   #1차원 배열로 만들어 순서를 찾기 쉽게 만든다. 
 
print('10번째 원소 : ', b[9])
print('20번째 원소 : ', b[19])

10번째 원소 :  9
20번째 원소 :  19


## 10.6

In [61]:
x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1, 10) for i in range(100)]
x3 = [i + np.random.randint(1, 50) for i in range(100)]
x4 = [np.random.randint(1, 100) for i in range(100)]

In [62]:
result = np.corrcoef([x1, x2, x3, x4])
print(result)

[[ 1.          0.9955585   0.89150635 -0.02964141]
 [ 0.9955585   1.          0.89318541 -0.04001767]
 [ 0.89150635  0.89318541  1.         -0.09283507]
 [-0.02964141 -0.04001767 -0.09283507  1.        ]]


(1) x1과 가장 상관관계가 높은 리스트는 x2이다.

(2) x1과 가장 상관관계가 낮은 리스트는 x4이다.